### ISSUE TITLE
report errors when make [thanks!]

### ISSUE THREAD

**Issue by chunkai-meng** [cpearce/HARM#2]
My Executing Processes:
1. git clone https://github.com/cpearce/HARM.git  
2. cd HARM  
3. git submodule init  
4. git submodule update  
>[root@container-cpp ~/Cpp/HARM]# git submodule update  
Cloning into 'googletest'...  
Warning: Permanently added the RSA host key for IP address   '192.30.255.112' to the list of known hosts.  
Permission denied (publickey).  
fatal: Could not read from remote repository.  
>Please make sure you have the correct access rights  
and the repository exists.  
Clone of 'git@github.com:google/googletest.git' into submodule path   'googletest' failed  

I think this is because of cloning in SSH way, so, I change to use Http link.

5. git clone https://github.com/google/googletest.git
6. cd build  
7. cmake ..  

The cmake .. result looks good with minor "-- Looking for pthread_create - not found"

>[root@container-cpp ~ /Cpp/HARM/build]# make
Scanning dependencies of target harm_main
[2% ] Building CXX object CMakeFiles/harm_main.dir/src/Apriori.cpp.o
[4% ] Building CXX object CMakeFiles/harm_main.dir/src/ConnectionTable.cpp.o
[6% ] Building CXX object CMakeFiles/harm_main.dir/src/CoocurrenceGraph.cpp.o
[9% ] Building CXX object CMakeFiles/harm_main.dir/src/DataStreamMining.cpp.o
[11%] Building CXX object CMakeFiles/harm_main.dir/src/FPNode.cpp.o
[13%] Building CXX object CMakeFiles/harm_main.dir/src/FPTree.cpp.o
In file included from /root/Cpp/HARM/src/InvertedDataSetIndex.h:24:0,
                 from /root/Cpp/HARM/src/FPTree.h:19,
                 from /root/Cpp/HARM/src/FPTree.cpp:15:
/root/Cpp/HARM/src/Options.h: In constructor 'Options::Options(double, eRunModeType, unsigned int, unsigned int, double, double, double, double, int)':
/root/Cpp/HARM/src/Options.h:66:30: error: 'numeric_limits' is not a member of 'std'
       min_discriminativeness(std::numeric_limits<double>::quiet_NaN()),
                              ^~~
/root/Cpp/HARM/src/Options.h:66:50: error: expected primary-expression before 'double'
       min_discriminativeness(std::numeric_limits<double>::quiet_NaN()),
                                                  ^~~~~~
....

**Comment by cpearce** [comment]
OK. The remote URL of the submodule needs to be the HTTPS URL.

I've not tried building HARM on Ubuntu recently. You could try adding:

find_package(Threads)

to CMakeLists.txt, as discussed here:
http://stackoverflow.com/a/31948969

**Comment by chunkai-meng** [comment]
I'm a beginner of cmake, sorry. I really don't know how to add it to CMakeLists.txt. But, coud you tell me where you build HARM?  So I can shift to another linux from docker hub.

**Comment by cpearce** [comment]
Normally I build on Windows or MacOS.

Please try adding "find_package(Threads)" (without the quotes) after line 9 in the CMakeLists.txt file in the project root directory.

**Comment by chunkai-meng** [comment]
Thank you so much! 
I try adding "find_package(Threads)" without luck. But I change to use my Mac and make it successfully!  👍 

========
Install [cmake](https://cmake.org/files/v3.8/cmake-3.8.0-rc3-Darwin-x86_64.dmg)
git clone https://github.com/cpearce/HARM.git  
cd HARM  
git clone https://github.com/google/googletest.git
mkdir build
cd build  
cmake ..  
make
